dim: 1280
num_layers: 2
n_hidden: 64
pair_dim: 20
dropout: 0.1
max_len: 1000
task: 'DELPHI'
save_dir: './weight'
num_recycle: 1
batch_size: 1
test_dataset_path: './Task_Single_dataset/Task_DELPHI/Test_355.csv'