dim: 1280
num_layers: 2
n_hidden: 64
pair_dim: 20
dropout: 0.15
max_len: 1000
task: 'GraphPPIS'
save_dir: './weight'
num_recycle: 1
batch_size: 1
test_dataset_path: './Task_Single_dataset/Task_GraphPPIS/Test_60.csv'